[versions]
# plugins
kotlin = "2.2.0"
changelog = "2.2.1"
intellijPlatform = "2.11.0"
qodana = "2024.3.3"
kover = "0.8.3"

[libraries]

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
